name: build
# trigger via either push to selected branches or on manual run
on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

permissions:
  contents: write
concurrency:
  group: ${{ github.ref }}-plugins
  cancel-in-progress: true

jobs:


#============================================
# =================== SETUP =================
# ===========================================
  get_plugins:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - id: set-matrix
        run: |
          matrix_json=$(cat .github/plugins.json | jq -c)
          echo "matrix=$matrix_json" >> $GITHUB_OUTPUT


#============================================
#=================== WINDOWS ================
#============================================
  build_windows:
    needs: get_plugins    
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix: ${{fromJson(needs.get_plugins.outputs.matrix)}}
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - name: Install packages
        run: |
          sudo apt-get -y update
          sudo apt-get -y install gcc-mingw-w64-i686 gcc-mingw-w64-x86-64 mingw-w64-tools

      - name: Download source
        run: |
         cd ${{ matrix.directory }}
         wget https://github.com/ClassiCube/ClassiCube/archive/master.zip
         unzip -q master.zip
         wget https://cs.classicube.net/client/latest/ClassiCube.exe -O cc-32.exe
         wget https://cs.classicube.net/client/latest/ClassiCube.64.exe -O cc-64.exe

      - name: Compile plugin
        env:
          WIN32_CC: "i686-w64-mingw32-gcc"
          WIN64_CC: "x86_64-w64-mingw32-gcc"
          INCS:  "-I ./ClassiCube-master/src/"
          FLAGS: "-O1 -shared -s -fno-stack-protector -fno-math-errno -Qn -Werror -L. -lClassiCube"
        run: |         
         cd ${{ matrix.directory }}
         WIN_FLAGS="${{ env.FLAGS }}"
         if [[ ${{ matrix.win_lite }} == "true" ]]; then
           WIN_FLAGS="$WIN_FLAGS -nostartfiles -Wl,--entry=0"
         fi

         rm -f ClassiCube.exe ClassiCube.def libClassiCube.a
         cp cc-32.exe ClassiCube.exe
         gendef ClassiCube.exe
         i686-w64-mingw32-dlltool -d ClassiCube.def -l libClassiCube.a -D ClassiCube.exe
         ${{ env.WIN32_CC }} *.c ${{ env.INCS }} $WIN_FLAGS -o ${{ matrix.out_name }}_32.dll

         rm -f ClassiCube.exe ClassiCube.def libClassiCube.a
         cp cc-64.exe ClassiCube.exe
         gendef ClassiCube.exe
         x86_64-w64-mingw32-dlltool -d ClassiCube.def -l libClassiCube.a -D ClassiCube.exe
         ${{ env.WIN64_CC }} *.c ${{ env.INCS }} $WIN_FLAGS -o ${{ matrix.out_name }}_64.dll
          

      - uses: ./.github/actions/upload_build
        with:
          SOURCE_FILE: '${{ matrix.directory }}/${{ matrix.out_name }}_32.dll'
          DEST_NAME:   '${{ matrix.out_name }}_windows_32.dll'
          GROUP_NAME:  '${{ matrix.out_name }}'
          GH_TOKEN:    '${{ secrets.GITHUB_TOKEN }}'

      - uses: ./.github/actions/upload_build
        with:
          SOURCE_FILE: '${{ matrix.directory }}/${{ matrix.out_name }}_64.dll'
          DEST_NAME:   '${{ matrix.out_name }}_windows_64.dll'
          GROUP_NAME:  '${{ matrix.out_name }}'
          GH_TOKEN:    '${{ secrets.GITHUB_TOKEN }}'


      - uses: ./.github/actions/notify_failure
        if: failure()
        with:
          NOTIFY_MESSAGE: 'Failed to produce ${{ matrix.out_name }} plugin for Windows'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL }}'


#============================================
#==================== LINUX =================
#============================================
  build_linux:
    needs: get_plugins    
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container:
      image: ubuntu:20.04
    strategy:
      max-parallel: 1
      matrix: ${{fromJson(needs.get_plugins.outputs.matrix)}}
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - name: Install packages
        run: |
          apt-get -y update
          apt-get -y install gcc-multilib wget curl unzip

      - name: Download source
        run: |
         cd ${{ matrix.directory }}
         wget https://github.com/ClassiCube/ClassiCube/archive/master.zip
         unzip -q master.zip

      - name: Compile plugin
        env:
          LIN32_CC: "gcc -m32"
          LIN64_CC: "gcc -m64"
          INCS:  "-I ./ClassiCube-master/src/"
          FLAGS: "-O1 -g -fno-stack-protector -fno-math-errno -Qn -fvisibility=hidden -nostartfiles -Wl,--entry=0 -shared -fPIC -Werror"
        run: |         
         cd ${{ matrix.directory }}
         ${{ env.LIN32_CC }} *.c ${{ env.INCS }} ${{ env.FLAGS }} -o ${{ matrix.out_name }}_32.so
         ${{ env.LIN64_CC }} *.c ${{ env.INCS }} ${{ env.FLAGS }} -o ${{ matrix.out_name }}_64.so
          

      - uses: ./.github/actions/upload_build
        with:
          SOURCE_FILE: '${{ matrix.directory }}/${{ matrix.out_name }}_32.so'
          DEST_NAME:   '${{ matrix.out_name }}_linux_32.so'
          GROUP_NAME:  '${{ matrix.out_name }}'
          GH_TOKEN:    '${{ secrets.GITHUB_TOKEN }}'

      - uses: ./.github/actions/upload_build
        with:
          SOURCE_FILE: '${{ matrix.directory }}/${{ matrix.out_name }}_64.so'
          DEST_NAME:   '${{ matrix.out_name }}_linux_64.so'
          GROUP_NAME:  '${{ matrix.out_name }}'
          GH_TOKEN:    '${{ secrets.GITHUB_TOKEN }}'


      - uses: ./.github/actions/notify_failure
        if: failure()
        with:
          NOTIFY_MESSAGE: 'Failed to produce ${{ matrix.out_name }} plugin for Linux'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL }}'


#============================================
#==================== MACOS =================
#============================================
  build_macos:
    needs: get_plugins    
    timeout-minutes: 10
    runs-on: macos-latest
    strategy:
      max-parallel: 1
      matrix: ${{fromJson(needs.get_plugins.outputs.matrix)}}
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - name: Download source
        run: |
         cd ${{ matrix.directory }}
         wget https://github.com/ClassiCube/ClassiCube/archive/master.zip
         unzip -q master.zip

      - name: Compile plugin
        env:
          MACINT_CC: "clang -arch x86_64"
          MACARM_CC: "clang -arch arm64"
          INCS:  "-I ./ClassiCube-master/src/"
          FLAGS: "-O1 -g -fno-stack-protector -fno-math-errno -Qn -shared -Werror -undefined dynamic_lookup -Wno-string-plus-int"
        run: |         
         cd ${{ matrix.directory }}
         ${{ env.MACINT_CC }} *.c ${{ env.INCS }} ${{ env.FLAGS }} -o ${{ matrix.out_name }}_int64.dylib
         ${{ env.MACARM_CC }} *.c ${{ env.INCS }} ${{ env.FLAGS }} -o ${{ matrix.out_name }}_arm64.dylib
         lipo -create -output ${{ matrix.out_name }}_64.dylib ${{ matrix.out_name }}_int64.dylib ${{ matrix.out_name }}_arm64.dylib


      - uses: ./.github/actions/upload_build
        with:
          SOURCE_FILE: '${{ matrix.directory }}/${{ matrix.out_name }}_64.dylib'
          DEST_NAME:   '${{ matrix.out_name }}_macos_64.dylib'
          GROUP_NAME:  '${{ matrix.out_name }}'
          GH_TOKEN:    '${{ secrets.GITHUB_TOKEN }}'


      - uses: ./.github/actions/notify_failure
        if: failure()
        with:
          NOTIFY_MESSAGE: 'Failed to produce ${{ matrix.out_name }} plugin for macOS'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL }}'


#============================================
#==================== RPI32 =================
#============================================
  build_rpi32:
    needs: get_plugins    
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container:
      image: dockcross/linux-armv6-lts
    strategy:
      max-parallel: 1
      matrix: ${{fromJson(needs.get_plugins.outputs.matrix)}}
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - name: Download source
        run: |
         cd ${{ matrix.directory }}
         wget https://github.com/ClassiCube/ClassiCube/archive/master.zip
         unzip -q master.zip

      - name: Compile plugin
        env:
          RPI_CC: "gcc"
          INCS:   "-I ./ClassiCube-master/src/"
          FLAGS:  "-O1 -g -fno-stack-protector -fno-math-errno -Qn -fvisibility=hidden -nostartfiles -Wl,--entry=0 -shared -fPIC -Werror"
        run: |         
         cd ${{ matrix.directory }}
         ${{ env.RPI_CC }} *.c ${{ env.INCS }} ${{ env.FLAGS }} -o ${{ matrix.out_name }}_32.so
          

      - uses: ./.github/actions/upload_build
        with:
          SOURCE_FILE: '${{ matrix.directory }}/${{ matrix.out_name }}_32.so'
          DEST_NAME:   '${{ matrix.out_name }}_raspberrypi_32.so'
          GROUP_NAME:  '${{ matrix.out_name }}'
          GH_TOKEN:    '${{ secrets.GITHUB_TOKEN }}'


      - uses: ./.github/actions/notify_failure
        if: failure()
        with:
          NOTIFY_MESSAGE: 'Failed to produce ${{ matrix.out_name }} plugin for RPi'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL }}'
