name: build
on: push
permissions:
  contents: write
jobs:


#============================================
# =================== SETUP =================
# ===========================================
  get_plugins:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - id: set-matrix
        run: |
          matrix_json=$(cat .github/plugins.json | jq -c)
          echo "matrix=$matrix_json" >> $GITHUB_OUTPUT


#============================================
# =================== LINUX =================
# ===========================================
  build_linux:
    needs: get_plugins    
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container:
      image: ubuntu:20.04
    strategy:
      max-parallel: 1
      matrix: ${{fromJson(needs.get_plugins.outputs.matrix)}}
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - name: Install packages
        run: |
          apt-get -y update
          apt-get -y install gcc-multilib wget curl unzip

      - name: Download source
        run: |
         cd ${{ matrix.directory }}
         wget github.com/ClassiCube/ClassiCube/archive/master.zip
         unzip -q master.zip

      - name: Compile plugin
        env:
          LIN32_CC: "gcc -m32"
          LIN64_CC: "gcc -m64"
          INCS:  "-I ./ClassiCube-master/src/"
          FLAGS: "-O1 -g -fno-stack-protector -fno-math-errno -Qn -nostartfiles -Wl,--entry=0 -shared -fPIC"
        run: |         
         cd ${{ matrix.directory }}
         ${{ env.LIN32_CC }} *.c ${{ env.INCS }} ${{ env.FLAGS }} -o ${{ matrix.out_name }}_32.so
         ${{ env.LIN64_CC }} *.c ${{ env.INCS }} ${{ env.FLAGS }} -o ${{ matrix.out_name }}_64.so
          

      - uses: ./.github/actions/upload_build
        with:
          SOURCE_FILE: '${{ matrix.directory }}/${{ matrix.out_name }}_32.so'
          DEST_NAME:   '${{ matrix.out_name }}_linux32.so'
          GROUP_NAME:  '${{ matrix.out_name }}'
          GH_TOKEN:    '${{ secrets.GITHUB_TOKEN }}'

      - uses: ./.github/actions/upload_build
        with:
          SOURCE_FILE: '${{ matrix.directory }}/${{ matrix.out_name }}_64.so'
          DEST_NAME:   '${{ matrix.out_name }}_linux64.so'
          GROUP_NAME:  '${{ matrix.out_name }}'
          GH_TOKEN:    '${{ secrets.GITHUB_TOKEN }}'
 
      
